---
- name: distrust ochami certificate
  become: true
  ansible.builtin.shell: 'trust anchor --remove /tmp/ochami.pem; update-ca-trust'

- name: delete ochami certificate
  become: true
  ansible.builtin.command: 'rm -f /tmp/ochami.pem'
