bss_kernel_version: '4.18.0-553.22.1.el8_10.x86_64'
bss_image_version: 'rocky/test'
bss_initrd_url: 'http://{{ cluster_boot_ip }}:8080/openchami/{{ bss_image_version }}/initramfs-{{ bss_kernel_version }}.img'
bss_kernel_url: 'http://{{ cluster_boot_ip }}:8080/openchami/{{ bss_image_version }}/vmlinuz-{{ bss_kernel_version }}'
bss_params_root: 'root=live:http://{{ cluster_boot_ip }}:8080/openchami/{{ bss_image_version }}/rootfs-{{ bss_kernel_version }}'
bss_params_cloud_init: 'ds=nocloud;s=http://{{ cluster_boot_ip }}:8081/cloud-init/'
#bss_params_cloud_init: 'ochami_wg_ip=10.89.2.6'
bss_params_opts: 'overlayroot=tmpfs overlayroot_cfgdisk=disabled nomodeset ro ip=dhcp apparmor=0 selinux=0 console=ttyS0,115200 ip6=off network-config=disabled rd.shell'
bss_params: '{{ bss_params_root }} {{ bss_params_cloud_init }} {{ bss_params_opts }}'

_bss_macs: |
        {% for item in nodes %}
        - {{ item.interfaces[0].mac_addr }}
        {% endfor %}
bss_macs: "{{ _bss_macs | from_yaml }}"
