bss_initrd_url: 'http://{{ cluster_boot_ip }}:8080/openchami/rocky/v1/initramfs-4.18.0-553.22.1.el8_10.x86_64.img'
bss_kernel_url: 'http://{{ cluster_boot_ip }}:8080/openchami/rocky/v1/vmlinuz-4.18.0-553.22.1.el8_10.x86_64'
bss_params_root: 'root=live:http://{{ cluster_boot_ip }}:8080/openchami/rocky/v1/rootfs-4.18.0-553.22.1.el8_10.x86_64'
bss_params_cloud_init: 'ochami_ci_url=http://{{ cluster_boot_ip }}:8081/cloud-init/ ochami_ci_url_secure=http://{{ cluster_boot_ip }}:8081/cloud-init-secure/'
bss_params_opts: 'overlayroot=tmpfs overlayroot_cfgdisk=disabled nomodeset ro ip=dhcp apparmor=0 selinux=0 console=ttyS0,115200 ip6=off network-config=disabled rd.shell'
bss_params: '{{ bss_params_root }} {{ bss_params_cloud_init }} {{ bss_params_opts }}'

_bss_macs: |
        {% for item in nodes %}
        - {{ item.mac }}
        {% endfor %}
bss_macs: "{{ _bss_macs | from_yaml }}"
