cluster_name: "stratus"
cluster_shortname: "st"
cluster_domain: "openchami.cluster"
cluster_boot_ip: 172.16.0.253
ochami_base_url: "https://{{ cluster_name }}.{{ cluster_domain }}:8443"
ochami_smd_url: "{{ ochami_base_url }}/hsm/v2"
ochami_bss_url: "{{ ochami_base_url }}/boot/v1"
ochami_cloud_init_url: "{{ ochami_base_url }}/cloud-init"
