cluster_name: "demo"
cluster_shortname: "nid"
cluster_domain: "openchami.cluster"
cluster_boot_ip: 172.16.0.254
cluster_boot_ssh_pub_key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDOOqpvVM+cyPim78QpohBXAdSOjGs/sBU1afQ3NbTL3I5ZRUDO0Fzt7NZI6MR3YzIG4D82qf9dIXxbqZlURGxUiO7ODblj5xCm85hms7gbwKVEAo/ESBvZnI81/PqWR4ALzVlvR+FDc6iEtEPON6S5NGgyM2lIdrHaXtpCH9k4ohWqashzBuE9A4FW8Z+xh7GV5FZn2fbkYFKOiPd9s8QX7cwwmKhxkn5w9xVemCaWi74/giW+HcKZbv8zR02J8LHUno/q/yc0YnBt+mdoZSJfqXehmFcK4f7kwVWFR7o9G5bT0qTW09c6blChCGX2EDnmbCOP1cuyQaacizfKHNVdhmgS/w8MOW8pDOjbRbMU7wYESOMiS1hLoLZuy1NcSdrLGiC6Z+/IqgJJJZRw3b9qZMaIoCLxm9yq3Um2hw/G6cFdO7qsHMVOIXWE24m7anhfwK7J3qHTfegQj6eqTUJ2oS3OEjoCBkyRj+VR1B/blwT2SbX+lPZ7MTIu3bAMHEs= root@st-head.si.usrc'

ochami_base_url: "https://{{ cluster_name }}.{{ cluster_domain }}:8443"
ochami_smd_url: "{{ ochami_base_url }}/hsm/v2"
ochami_bss_url: "{{ ochami_base_url }}/boot/v1"
ochami_cloud_init_url: "{{ ochami_base_url }}/cloud-init"
