# The can be encrypted with ansible vault
postgres_password: supersecretpostgrespasswd
bss_postgres_password: supersecretbsspasswd
smd_postgres_password: supersecretsmdpasswd
hydra_postgres_password: supersecrethydrapasswd
hydra_system_secret: supersecretsystempasswd
hydra_dsn: 'postgres://hydra-user:{{ hydra_postgres_password }}@postgres:5432/hydradb?sslmode=disable&max_conns=20&max_idle_conns=4'
postgres_multiple_databases: 'hmsds:smd-user:{{ smd_postgres_password }},bssdb:bss-user:{{ bss_postgres_password }},hydradb:hydra-user:{{ hydra_postgres_password }}'

podman_secrets:
  - name: postgres_password
    data: '{{ postgres_password }}'
  - name: bss_postgres_password
    data: '{{ bss_postgres_password }}'
  - name: smd_postgres_password
    data: '{{ smd_postgres_password }}'
  - name: hydra_postgres_password
    data: '{{ hydra_postgres_password }}'
  - name: hydra_system_secret
    data: '{{ hydra_system_secret }}'
  - name: hydra_dsn
    data: '{{ hydra_dsn }}'
  - name: postgres_multiple_databases
    data: '{{ postgres_multiple_databases }}'
