{{- if .Capabilities.APIVersions.Has "cloud.google.com/v1" }}
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: krakend-hc-config
  namespace: {{ .Release.Namespace }}
spec:
  healthCheck:
    checkIntervalSec: 30
    port: {{ .Values.krakend.deployment.containerPort }}
    type: HTTP
    requestPath: /__health
  securityPolicy:
    name: {{ default "" .Values.gke.securityPolicy }}
{{- end }}
