---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: krakend
  namespace: {{ .Release.Namespace }}
  labels:
    app: krakend
spec:
  replicas: {{ .Values.krakend.deployment.replicaCount }}
  selector:
    matchLabels:
      app: krakend
  template:
    metadata:
      labels:
        app: krakend
    spec:
      containers:
      - name: krakend
        image: {{ .Values.krakend.deployment.image.repository }}/{{ .Values.krakend.deployment.image.name }}:{{ .Values.krakend.deployment.image.tag }}
        imagePullPolicy: {{ .Values.krakend.deployment.image.pullPolicy }}
        args: ["run", "-c", "/etc/krakend/krakend-config.json"]
        env:
          # GKE bug: https://github.com/krakend/krakend-ce/issues/260
        - name: KRAKEND_PORT
          value: "{{ .Values.krakend.deployment.containerPort }}"
        ports:
        - name: krakend
          containerPort: {{ .Values.krakend.deployment.containerPort }}
          protocol: TCP
        volumeMounts:
        - name: krakend-config
          mountPath: /etc/krakend
          readOnly: true
        readinessProbe:
          httpGet:
            path: /__health
            port: {{ .Values.krakend.deployment.containerPort }}
      volumes:
      - name: krakend-config
        configMap:
          name: krakend-config
