---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: krakend-external
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
  - name: krakend-gateway
  rules:
  - backendRefs:
    - name: krakend
      namespace: {{ .Release.Namespace }}
      port: {{ .Values.krakend.service.port }}
