---
apiVersion: v1
data:
  krakend-config.json: |
    {
      "$schema": "https://www.krakend.io/schema/krakend.json",
      "version": 3,
      "name": "KrakenD - API Gateway",
      "extra_config": {
        "telemetry/logging": {
          "level": "ERROR",
          "prefix": "[KRAKEND]",
          "syslog": false,
          "stdout": true,
          "format": "default",
          "syslog_facility": "local3"
        },
        "documentation/openapi": {
          "version": "1.0"
        }
      },
      "timeout": "3000ms",
      "cache_ttl": "300s",
      "output_encoding": "json",
      "port": {{ .Values.krakend.deployment.containerPort }},
      "debug_endpoint": true,
      "echo_endpoint": true,
      "endpoints": [
        {
          "endpoint": "/bss/{item}",
          "method": "GET",
          "backend": [
            {
              "url_pattern": "/{item}",
              "method": "GET",
              "host": [
                "bss.ochami.svc.cluster.local:{{ .Values.bss.service.port }}"
              ]
            }
          ]
        },
        {
          "endpoint": "/bss/{item}",
          "method": "PUT",
          "backend": [
            {
              "url_pattern": "/{item}",
              "method": "PUT",
              "host": [
                "bss.ochami.svc.cluster.local:{{ .Values.bss.service.port }}"
              ]
            }
          ]
        },
        {
          "endpoint": "/bss/{item}",
          "method": "POST",
          "backend": [
            {
              "url_pattern": "/{item}",
              "method": "POST",
              "host": [
                "bss.ochami.svc.cluster.local:{{ .Values.bss.service.port }}"
              ]
            }
          ]
        },
        {
          "endpoint": "/bss/{item}",
          "method": "PATCH",
          "backend": [
            {
              "url_pattern": "/{item}",
              "method": "PATCH",
              "host": [
                "bss.ochami.svc.cluster.local:{{ .Values.bss.service.port }}"
              ]
            }
          ]
        },
        {
          "endpoint": "/bss/{item}",
          "method": "DELETE",
          "backend": [
            {
              "url_pattern": "/{item}",
              "method": "DELETE",
              "host": [
                "bss.ochami.svc.cluster.local:{{ .Values.bss.service.port }}"
              ]
            }
          ]
        },
        {
          "endpoint": "/bss/v1/{item1}",
          "method": "GET",
          "backend": [
            {
              "url_pattern": "/boot/v1/{item1}",
              "method": "GET",
              "host": [
                "bss.ochami.svc.cluster.local:{{ .Values.bss.service.port }}"
              ]
            }
          ]
        },
        {
          "endpoint": "/bss/v1/{item1}",
          "method": "POST",
          "backend": [
            {
              "url_pattern": "/boot/v1/{item1}",
              "method": "POST",
              "host": [
                "bss.ochami.svc.cluster.local:{{ .Values.bss.service.port }}"
              ]
            }
          ]
        },
        {
          "endpoint": "/bss/v1/{item1}",
          "method": "PUT",
          "backend": [
            {
              "url_pattern": "/boot/v1/{item1}",
              "method": "PUT",
              "host": [
                "bss.ochami.svc.cluster.local:{{ .Values.bss.service.port }}"
              ]
            }
          ]
        },
        {
          "endpoint": "/bss/v1/{item1}",
          "method": "PATCH",
          "backend": [
            {
              "url_pattern": "/boot/v1/{item1}",
              "method": "PATCH",
              "host": [
                "bss.ochami.svc.cluster.local:{{ .Values.bss.service.port }}"
              ]
            }
          ]
        },
        {
          "endpoint": "/bss/v1/{item1}",
          "method": "DELETE",
          "backend": [
            {
              "url_pattern": "/boot/v1/{item1}",
              "method": "DELETE",
              "host": [
                "bss.ochami.svc.cluster.local:{{ .Values.bss.service.port }}"
              ]
            }
          ]
        },
        {
          "endpoint": "/bss/v1/{item1}/{item2}",
          "method": "GET",
          "backend": [
            {
              "url_pattern": "/boot/v1/{item1}/{item2}",
              "method": "GET",
              "host": [
                "bss.ochami.svc.cluster.local:{{ .Values.bss.service.port }}"
              ]
            }
          ]
        },
        {
          "endpoint": "/bss/v1/{item1}/{item2}",
          "method": "POST",
          "backend": [
            {
              "url_pattern": "/boot/v1/{item1}/{item2}",
              "method": "POST",
              "host": [
                "bss.ochami.svc.cluster.local:{{ .Values.bss.service.port }}"
              ]
            }
          ]
        },
        {
          "endpoint": "/bss/v1/{item1}/{item2}",
          "method": "PUT",
          "backend": [
            {
              "url_pattern": "/boot/v1/{item1}/{item2}",
              "method": "PUT",
              "host": [
                "bss.ochami.svc.cluster.local:{{ .Values.bss.service.port }}"
              ]
            }
          ]
        },
        {
          "endpoint": "/bss/v1/{item1}/{item2}",
          "method": "PATCH",
          "backend": [
            {
              "url_pattern": "/boot/v1/{item1}/{item2}",
              "method": "PATCH",
              "host": [
                "bss.ochami.svc.cluster.local:{{ .Values.bss.service.port }}"
              ]
            }
          ]
        },
        {
          "endpoint": "/bss/v1/{item1}/{item2}",
          "method": "DELETE",
          "backend": [
            {
              "url_pattern": "/boot/v1/{item1}/{item1}",
              "method": "DELETE",
              "host": [
                "bss.ochami.svc.cluster.local:{{ .Values.bss.service.port }}"
              ]
            }
          ]
        },
        {
          "endpoint": "/hsm/v2/{item1}",
          "method": "GET",
          "backend": [
            {
              "url_pattern": "/hsm/v2/{item1}",
              "method": "GET",
              "host": [
                "smd.ochami.svc.cluster.local:{{ .Values.smd.service.port }}"
              ]
            }
          ]
        },
        {
          "endpoint": "/hsm/v2/{item1}",
          "method": "PUT",
          "backend": [
            {
              "url_pattern": "/hsm/v2/{item1}",
              "method": "PUT",
              "host": [
                "smd.ochami.svc.cluster.local:{{ .Values.smd.service.port }}"
              ]
            }
          ]
        },
        {
          "endpoint": "/hsm/v2/{item1}",
          "method": "POST",
          "backend": [
            {
              "url_pattern": "/hsm/v2/{item1}",
              "method": "POST",
              "host": [
                "smd.ochami.svc.cluster.local:{{ .Values.smd.service.port }}"
              ]
            }
          ]
        },
        {
          "endpoint": "/hsm/v2/{item1}",
          "method": "PATCH",
          "backend": [
            {
              "url_pattern": "/hsm/v2/{item1}",
              "method": "PATCH",
              "host": [
                "smd.ochami.svc.cluster.local:{{ .Values.smd.service.port }}"
              ]
            }
          ]
        },
        {
          "endpoint": "/hsm/v2/{item1}",
          "method": "DELETE",
          "backend": [
            {
              "url_pattern": "/hsm/v2/{item1}",
              "method": "DELETE",
              "host": [
                "smd.ochami.svc.cluster.local:{{ .Values.smd.service.port }}"
              ]
            }
          ]
        },
        {
          "endpoint": "/hsm/v2/{item1}/{item2}",
          "method": "GET",
          "backend": [
            {
              "url_pattern": "/hsm/v2/{item1}/{item2}",
              "method": "GET",
              "host": [
                "smd.ochami.svc.cluster.local:{{ .Values.smd.service.port }}"
              ]
            }
          ]
        },
        {
          "endpoint": "/hsm/v2/{item1}/{item2}",
          "method": "PUT",
          "backend": [
            {
              "url_pattern": "/hsm/v2/{item1}/{item2}",
              "method": "PUT",
              "host": [
                "smd.ochami.svc.cluster.local:{{ .Values.smd.service.port }}"
              ]
            }
          ]
        },
        {
          "endpoint": "/hsm/v2/{item1}/{item2}",
          "method": "POST",
          "backend": [
            {
              "url_pattern": "/hsm/v2/{item1}/{item2}",
              "method": "POST",
              "host": [
                "smd.ochami.svc.cluster.local:{{ .Values.smd.service.port }}"
              ]
            }
          ]
        },
        {
          "endpoint": "/hsm/v2/{item1}/{item2}",
          "method": "PATCH",
          "backend": [
            {
              "url_pattern": "/hsm/v2/{item1}/{item2}",
              "method": "PATCH",
              "host": [
                "smd.ochami.svc.cluster.local:{{ .Values.smd.service.port }}"
              ]
            }
          ]
        },
        {
          "endpoint": "/hsm/v2/{item1}/{item2}",
          "method": "DELETE",
          "backend": [
            {
              "url_pattern": "/hsm/v2/{item1}/{item2}",
              "method": "DELETE",
              "host": [
                "smd.ochami.svc.cluster.local:{{ .Values.smd.service.port }}"
              ]
            }
          ]
        },
        {
          "endpoint": "/hsm/v2/{item1}/{item2}/{item3}",
          "method": "GET",
          "backend": [
            {
              "url_pattern": "/hsm/v2/{item1}/{item2}/{item3}",
              "method": "GET",
              "host": [
                "smd.ochami.svc.cluster.local:{{ .Values.smd.service.port }}"
              ]
            }
          ]
        },
        {
          "endpoint": "/hsm/v2/{item1}/{item2}/{item3}",
          "method": "PUT",
          "backend": [
            {
              "url_pattern": "/hsm/v2/{item1}/{item2}/{item3}",
              "method": "PUT",
              "host": [
                "smd.ochami.svc.cluster.local:{{ .Values.smd.service.port }}"
              ]
            }
          ]
        },
        {
          "endpoint": "/hsm/v2/{item1}/{item2}/{item3}",
          "method": "POST",
          "backend": [
            {
              "url_pattern": "/hsm/v2/{item1}/{item2}/{item3}",
              "method": "POST",
              "host": [
                "smd.ochami.svc.cluster.local:{{ .Values.smd.service.port }}"
              ]
            }
          ]
        },
        {
          "endpoint": "/hsm/v2/{item1}/{item2}/{item3}",
          "method": "PATCH",
          "backend": [
            {
              "url_pattern": "/hsm/v2/{item1}/{item2}/{item3}",
              "method": "PATCH",
              "host": [
                "smd.ochami.svc.cluster.local:{{ .Values.smd.service.port }}"
              ]
            }
          ]
        },
        {
          "endpoint": "/hsm/v2/{item1}/{item2}/{item3}",
          "method": "DELETE",
          "backend": [
            {
              "url_pattern": "/hsm/v2/{item1}/{item2}/{item3}",
              "method": "DELETE",
              "host": [
                "smd.ochami.svc.cluster.local:{{ .Values.smd.service.port }}"
              ]
            }
          ]
        },
        {
          "endpoint": "/hsm/v2/{item1}/{item2}/{item3}/{item4}",
          "method": "GET",
          "backend": [
            {
              "url_pattern": "/hsm/v2/{item1}/{item2}/{item3}/{item4}",
              "method": "GET",
              "host": [
                "smd.ochami.svc.cluster.local:{{ .Values.smd.service.port }}"
              ]
            }
          ]
        },
        {
          "endpoint": "/hsm/v2/{item1}/{item2}/{item3}/{item4}",
          "method": "PUT",
          "backend": [
            {
              "url_pattern": "/hsm/v2/{item1}/{item2}/{item3}/{item4}",
              "method": "PUT",
              "host": [
                "smd.ochami.svc.cluster.local:{{ .Values.smd.service.port }}"
              ]
            }
          ]
        },
        {
          "endpoint": "/hsm/v2/{item1}/{item2}/{item3}/{item4}",
          "method": "POST",
          "backend": [
            {
              "url_pattern": "/hsm/v2/{item1}/{item2}/{item3}/{item4}",
              "method": "POST",
              "host": [
                "smd.ochami.svc.cluster.local:{{ .Values.smd.service.port }}"
              ]
            }
          ]
        },
        {
          "endpoint": "/hsm/v2/{item1}/{item2}/{item3}/{item4}",
          "method": "PATCH",
          "backend": [
            {
              "url_pattern": "/hsm/v2/{item1}/{item2}/{item3}/{item4}",
              "method": "PATCH",
              "host": [
                "smd.ochami.svc.cluster.local:{{ .Values.smd.service.port }}"
              ]
            }
          ]
        },
        {
          "endpoint": "/hsm/v2/{item1}/{item2}/{item3}/{item4}",
          "method": "DELETE",
          "backend": [
            {
              "url_pattern": "/hsm/v2/{item1}/{item2}/{item3}/{item4}",
              "method": "DELETE",
              "host": [
                "smd.ochami.svc.cluster.local:{{ .Values.smd.service.port }}"
              ]
            }
          ]
        },
        {
          "endpoint": "/hsm/v2/{item1}/{item2}/{item3}/{item4}/{item5}",
          "method": "GET",
          "backend": [
            {
              "url_pattern": "/hsm/v2/{item1}/{item2}/{item3}/{item4}/{item5}",
              "method": "GET",
              "host": [
                "smd.ochami.svc.cluster.local:{{ .Values.smd.service.port }}"
              ]
            }
          ]
        },
        {
          "endpoint": "/hsm/v2/{item1}/{item2}/{item3}/{item4}/{item5}",
          "method": "PUT",
          "backend": [
            {
              "url_pattern": "/hsm/v2/{item1}/{item2}/{item3}/{item4}/{item5}",
              "method": "PUT",
              "host": [
                "smd.ochami.svc.cluster.local:{{ .Values.smd.service.port }}"
              ]
            }
          ]
        },
        {
          "endpoint": "/hsm/v2/{item1}/{item2}/{item3}/{item4}/{item5}",
          "method": "POST",
          "backend": [
            {
              "url_pattern": "/hsm/v2/{item1}/{item2}/{item3}/{item4}/{item5}",
              "method": "POST",
              "host": [
                "smd.ochami.svc.cluster.local:{{ .Values.smd.service.port }}"
              ]
            }
          ]
        },
        {
          "endpoint": "/hsm/v2/{item1}/{item2}/{item3}/{item4}/{item5}",
          "method": "PATCH",
          "backend": [
            {
              "url_pattern": "/hsm/v2/{item1}/{item2}/{item3}/{item4}/{item5}",
              "method": "PATCH",
              "host": [
                "smd.ochami.svc.cluster.local:{{ .Values.smd.service.port }}"
              ]
            }
          ]
        },
        {
          "endpoint": "/hsm/v2/{item1}/{item2}/{item3}/{item4}/{item5}",
          "method": "DELETE",
          "backend": [
            {
              "url_pattern": "/hsm/v2/{item1}/{item2}/{item3}/{item4}/{item5}",
              "method": "DELETE",
              "host": [
                "smd.ochami.svc.cluster.local:{{ .Values.smd.service.port }}"
              ]
            }
          ]
        }
      ]
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: krakend-config
  namespace: ochami
