apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: krakend
  {{- with .Values.krakend.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.krakend.service.type }}
  ports:
    - port: {{ .Values.krakend.service.port }}
      targetPort: {{ .Values.krakend.deployment.containerPort }}
      name: krakend
  selector:
    app: krakend
