apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mgmt

resources:
- cluster.yaml

# What I wouldn't give for a systemd-esque dependency chain system.
# Overall, we want the order to be:
# - 5 CNPG itself
# - 10 The CNPG Cluster and role Secrets
# - 15 The Databases
# - 20 Migration Jobs. Need to think how these will be handled past init
# - 30 SMD
# - 35 A static discover Job? Maybe?
# - 40 Services that aren't SMD
commonAnnotations:
  argocd.argoproj.io/sync-wave: "10"
