{{- if .Capabilities.APIVersions.Has "cloud.google.com/v1" }}
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: lighttpd-backendconfig
  namespace: {{ .Release.Namespace }}
spec:
  healthCheck:
    checkIntervalSec: 30
    port: {{ .Values.krakend.deployment.containerPort }}
    type: HTTP
    requestPath: /foo
  securityPolicy:
    name: {{ default "" .Values.gke.securityPolicy }}
{{- end }}
