---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: lighttpd-gateway
  namespace: {{ .Release.Namespace }}
spec:
  gatewayClassName: {{ .Values.gke.gateway.class }}
  listeners:
  - name: http
    protocol: HTTP
    port: {{ .Values.gke.gateway.port }}
