---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: lighttpd-httproute
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
  - name: lighttpd-gateway
  rules:
  - backendRefs:
    - name: lighttpd
      namespace: {{ .Release.Namespace }}
      port: {{ .Values.lighttpd.service.port }}
