apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: lighttpd
  {{- with .Values.lighttpd.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.lighttpd.service.type }}
  ports:
    - port: {{ .Values.lighttpd.service.port }}
      targetPort: {{ .Values.lighttpd.deployment.containerPort }}
      name: lighttpd
  selector:
    app: lighttpd
