---
- name: Populate cloud-init
  ansible.builtin.uri:
    url: '{{ ochami_cloud_init_url }}/{{ item.name }}'
    method: "DELETE"
    status_code:
      - 200
      - 201
      - 405
    headers:
      Authorization: 'Bearer {{ access_token.stdout }}'
  with_items:
    - '{{ cluster_cloud_init }}'

- name: Populate cloud-init
  ansible.builtin.uri:
    url: '{{ ochami_cloud_init_url }}'
    method: "POST"
    status_code:
      - 200
      - 201
    headers:
      Authorization: 'Bearer {{ access_token.stdout }}'
    body_format: json
    body:
      name: '{{ item.name }}'
      cloud-init: '{{ item.cloud_init }}'
  with_items:
    - '{{ cluster_cloud_init }}'


- name: Populate cloud-init-secure
  ansible.builtin.uri:
    url: '{{ ochami_cloud_init_url }}-secure/{{ item.name }}'
    method: "DELETE"
    status_code:
      - 200
      - 201
      - 405
    headers:
      Authorization: 'Bearer {{ access_token.stdout }}'
  with_items:
    - '{{ cluster_cloud_init_secure }}'

- name: Populate cloud-init-secure
  ansible.builtin.uri:
    url: '{{ ochami_cloud_init_url }}-secure'
    method: "POST"
    status_code:
      - 200
      - 201
    headers:
      Authorization: 'Bearer {{ access_token.stdout }}'
    body_format: json
    body:
      name: '{{ item.name }}'
      cloud-init: '{{ item.cloud_init }}'
  with_items:
    - '{{ cluster_cloud_init_secure }}'
