---
### POST service configs
- name: Update cloud-init default values
  ansible.builtin.uri:
    url: '{{ ochami_cloud_init_url }}/admin/cluster-defaults'
    method: 'POST'
    status_code:
      - 200
      - 201
    body_format: json
    headers:
      Authorization: 'Bearer {{ access_token.stdout }}'
    body:
      "cluster-name": '{{ cluster_name }}'
      "short-name": '{{ cluster_shortname }}'
      "nid-length": '{{ cluster_nidlength }}'
      "base-url": 'http://{{ cloud_init_wireguard_server }}:{{ cloud_init_wireguard_port }}/cloud-init'
      "public-keys": [
              '{{ cluster_boot_ssh_pub_key }}'
              ]

### Process template groups
- block:
    - name: write templates to file
      copy:
        content: '{{ cluster_cloud_init_combined_templates }}'
        dest: /etc/ochami/cloud-init-templates-raw.json
    - name: POST new cloud-init templates
      shell: |
        ochami cloud-init group set -d @/etc/ochami/cloud-init-templates-raw.json

    - name: write meta-data to file
      copy:
        content: '{{ cluster_cloud_init_combined_metadata }}'
        dest: /etc/ochami/cloud-init-meta-data-raw.json
    - name: POST new cloud-init templates
      shell: |
        ochami cloud-init group set -d @/etc/ochami/cloud-init-meta-data-raw.json
