### check if content of template has changed
- block: 
  - name: '{{ tmplt.name }} | Get cloud-init content'
    set_fact:
      group_cloud_init_data: >-
        {%- if 'meta-data' in existing_cloud_init_content[tmplt.name] -%}
        {{ existing_cloud_init_content[tmplt.name]['meta-data'] | b64encode }}
        {%- else -%}
        "group has no meta-data"
        {%- endif -%}
  
  - name: '{{ tmplt.name }} | Get inventory content'
    set_fact:
      group_inventory_data: '{{ tmplt["meta-data"] | b64encode }}'
  
  - name: '{{ tmplt.name }} | Set changed if contents do not match'
    set_fact:
      cloud_init_changed: true
    when: group_cloud_init_data != group_inventory_data

- name: '{{ tmplt.name }} | Update existing cloud-init templates'
  ansible.builtin.uri:
    url: '{{ ochami_cloud_init_url }}/admin/groups/{{ tmplt.name }}'
    method: "PUT"
    status_code:
      - 200
      - 201
    headers:
      Authorization: 'Bearer {{ access_token.stdout }}'
    body_format: json
    body:
      '{{ tmplt }}'
  changed_when: cloud_init_changed
  when:
    - cloud_init_changed | default(false) | bool
