apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cnpg.yaml

labels:
- includeSelectors: false
  pairs:
    app.kubernetes.io/component: smd

commonAnnotations:
  argocd.argoproj.io/sync-wave: "15"
