regctl_url: https://github.com/regclient/regclient/releases/latest/download/regctl-linux-amd64
regctl_dest: /usr/local/bin/regctl
ochami_work_dir: /opt/workdir
file_perm_rwx: 0755
file_perm_rw: 0644
epel10_url: https://dl.fedoraproject.org/pub/epel/epel-release-latest-10.noarch.rpm
epel10_gpg_key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-10
rhel_base_image_name: rhel-base
rhel_base_image: '{{ cluster_name }}/{{ rhel_base_image_name }}'
rhel_base_image_template: images/rhel-base.yaml.j2
rhel_base_compute_image_name: rhel-compute
rhel_base_compute_image: '{{ cluster_name }}/{{ rhel_base_compute_image_name }}'
rhel_base_compute_image_template: images/rhel-base-compute.yaml.j2
image_build_fail_msg: "Error encountered while building image. This can be due to invalid url, packages or network issues."
