- name: Print libvirt networks
  debug:
    msg: '{{ item }}'
  with_items:
    - '{{ libvirt_nets }}'

- name: Define libvirt networks
  community.libvirt.virt_net:
    command: define
    name: '{{ item.name }}'
    xml: '{{ lookup("template", "vm-network.xml.j2") }}'
  with_items:
    - '{{ libvirt_nets }}'

- name: Start libvirt networks
  community.libvirt.virt_net:
    command: create
    name: '{{ item.name }}'
  with_items:
    - '{{ libvirt_nets }}'

- name: Print libvirt VMs
  debug:
    msg: '{{ item }}'
  with_items:
    - '{{ libvirt_vms }}'

- name: Define libvirt VMs
  community.libvirt.virt:
    command: define
    xml: "{{ lookup('template', 'vm.xml.j2') }}"
  with_items:
    - '{{ libvirt_vms }}'

- name: Start libvirt VMs
  community.libvirt.virt:
    name: '{{ item.name }}'
    state: running
  with_items:
    - '{{ libvirt_vms }}'
