apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: smd

commonAnnotations:
  argocd.argoproj.io/sync-wave: "30"
