---
- name: get ochami certificate
  ansible.builtin.shell: '/bin/bash -l -c "get_ca_cert > /etc/pki/ca-trust/source/anchors/ochami_tmp.pem"'

- name: trust ochami certificate
  ansible.builtin.shell: 'update-ca-trust'
  notify: distrust ochami certificate

- name: obtain access token to write to smd
  ansible.builtin.command: '/bin/bash -l -c " gen_access_token"'
  register: access_token
