# Using this monstrosity until we can figure out a way to speed up an ansible way of populating SMD
- name: Populate SMD with ochami-cli
  ansible.builtin.command:
    argv:
      - /bin/ochami
      - --token
      - "{{ access_token.stdout }}"
      - discover
      - -f
      - "/etc/ochami/nodes.yaml"
      - --payload-format
      - yaml
