# Using this monstrosity until we can figure out a way to speed up an ansible way of populating SMD
- name: Populate SMD with ochami CLI
  ansible.builtin.command:
    argv:
      - /usr/bin/ochami
      - --token
      - "{{ access_token.stdout }}"
      - discover
      - --payload
      - "/etc/ochami/nodes.yaml"
      - --payload-format
      - yaml

- name: Populate SMD groups with ochami CLI
  ansible.builtin.command:
    argv:
      - /usr/bin/ochami
      - --token
      - "{{ access_token.stdout }}"
      - smd
      - group
      - add
      - --payload
      - "/etc/ochami/groups.yaml"
      - --payload-format
      - yaml
