apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

resources:
- vm.yaml
- dv_fedora.yaml
- bmc.yaml

labels:
- includeSelectors: false
  pairs:
    virtfish.example/component: vm

commonAnnotations:
  argocd.argoproj.io/sync-wave: "5"
