kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: ochami
  name: haproxy-certs
spec:
  storageClassName: ceph-cephfs-external
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
