kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: ochami
  name: step-ca-home
spec:
  storageClassName: ceph-cephfs-external
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
