apiVersion: v1
kind: Secret
metadata:
  namespace: ochami
  name: env-secrets
stringData:
  SYSTEM_NAME: razorback
  SYSTEM_DOMAIN: openchami.cluster
  POSTGRES_USER: ochami
  POSTGRES_PASSWORD: ASDF
  BSS_POSTGRES_PASSWORD: ASDF
  SMD_POSTGRES_PASSWORD: ASDF
  HYDRA_POSTGRES_PASSWORD: ASDF
  HYDRA_SYSTEM_SECRET: ASDF
  LOCAL_IP: A.S.D.F
