apiVersion: v1
kind: Service
metadata:
  namespace: ochami
  name: webserver
spec:
  selector:
    app.kubernetes.io/name: webserver
  type: LoadBalancer
  loadBalancerIP: 192.168.0.0
  ports:
    - name: http
      port: 80
      targetPort: 8000
