apiVersion: v1
kind: Service
metadata:
  namespace: ochami
  name: dnsmasq-nmn
spec:
  selector:
    app.kubernetes.io/name: dnsmasq
  type: LoadBalancer
  loadBalancerIP: 192.168.0.0
  ports:
    - name: dnsmasq-dns
      port: 53
      protocol: UDP
    - name: dnsmasq-dhcp
      port: 67
      protocol: UDP
    - name: dnsmasq-tftp
      port: 69
      protocol: UDP

---

apiVersion: v1
kind: Service
metadata:
  namespace: ochami
  name: dnsmasq-hmn
spec:
  selector:
    app.kubernetes.io/name: dnsmasq
  type: LoadBalancer
  loadBalancerIP: 192.168.0.0
  ports:
    - name: dnsmasq-dns
      port: 53
      protocol: UDP
    - name: dnsmasq-dhcp
      port: 67
      protocol: UDP
