apiVersion: v1
kind: Service
metadata:
  namespace: ochami
  name: haproxy
spec:
  selector:
    app.kubernetes.io/name: haproxy-gateway
  type: LoadBalancer
  loadBalancerIP: 192.168.0.0
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
