apiVersion: v1
data:
  hydra.yml: |
    ---
    serve:
      cookies:
        same_site_mode: Lax

    urls:
      self:
        issuer: http://127.0.0.1:4444
      consent: http://127.0.0.1:3000/consent
      login: http://127.0.0.1:3000/login
      logout: http://127.0.0.1:3000/logout

    secrets:
      system:
        - ${HYDRA_SYSTEM_SECRET} # set in .env

    oidc:
      dynamic_client_registration:
        enabled: true
      subject_identifiers:
        supported_types:
          - pairwise
          - public
        pairwise:
          salt: ${HYDRA_OIDC_SALT} # set in .env

    oauth2:
      grant:
        jwt:
          jti_optional: true
          iat_optional: true
          max_ttl: 24h

    strategies:
      access_token: jwt
kind: ConfigMap
metadata:
  name: hydra-config
  namespace: {{ .Release.Namespace }}
