

# roles/keylime_registrar/tasks/main.yml
- name: Ensure registrar config directory exists
  file:
    path: /etc/keylime/registrar.conf.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Configure registrar (bind IP and TLS)
  copy:
    dest: /etc/keylime/registrar.conf.d/00-registrar.conf
    content: |
      [registrar]
      ip = 0.0.0.0
      tls_dir = /var/lib/keylime/cv_ca
      server_cert = server-cert.crt
      server_key = server-private.pem
      trusted_client_ca = cacert.crt
    owner: root
    group: root
    mode: '0644'
  notify: Restart keylime-registrar

- name: Deploy Keylime Registrar Quadlet service
  copy:
    dest: /etc/containers/systemd/keylime-registrar.container
    content: |
      [Unit]
      Description=Keylime Registrar Service (Podman)
      After=network-online.target
      Wants=network-online.target

      [Service]
      Restart=always

      [Container]
      Image=registry.access.redhat.com/rhel9/keylime-registrar:latest
      ContainerName=keylime-registrar
      Environment=TPM2TOOLS_TCTI=device:/dev/tpmrm0
      PublishPort=8890:8890
      PublishPort=8891:8891
      Volume=/etc/keylime/registrar.conf.d:/etc/keylime/registrar.conf.d:Z
      Volume=/var/lib/keylime/cv_ca:/var/lib/keylime/cv_ca:Z

      [Install]
      WantedBy=multi-user.target
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload systemd           # Reload unit files if changed
    - Restart keylime-registrar

- name: Enable and start Keylime Registrar service
  systemd:
    name: keylime-registrar.service
    enabled: true
    state: started
