---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smd
  namespace: {{ .Release.Namespace }}
  labels:
    app: smd
spec:
  replicas: {{ .Values.smd.deployment.replicaCount }}
  selector:
    matchLabels:
      app: smd
  template:
    metadata:
      labels:
        app: smd
    spec:
      containers:
        - name: smd
          image: {{ .Values.smd.deployment.image.repository }}/{{ .Values.smd.deployment.image.name }}:{{ .Values.smd.deployment.image.tag }}
          imagePullPolicy: {{ .Values.smd.deployment.image.pullPolicy }}
          ports:
            - name: smd
              containerPort: {{ .Values.smd.deployment.containerPort }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /hsm/v2/service/ready
              port: {{ .Values.smd.deployment.containerPort }}
          env:
            - name: SMD_DBHOST
              value: {{ .Release.Name }}-postgresql-smd.{{ .Release.Namespace }}.svc.cluster.local
            - name: SMD_DBPORT
              value: "{{ .Values.postgres.deployment.containerPort }}"
            - name: SMD_DBUSER
              value: smd-user
            - name: SMD_DBPASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgresql-smd
                  key: password
            - name: SMD_DBNAME
              value: {{ .Values.smd.dbname }}
            - name: SMD_DBOPTS
              value: sslmode=disable
