---
apiVersion: batch/v1
kind: Job
metadata:
  name: smd
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      containers:
        - name: smd-init
          image: {{ .Values.smd.deployment.image.repository }}/{{ .Values.smd.deployment.image.name }}:{{ .Values.smd.deployment.image.tag }}
          imagePullPolicy: {{ .Values.smd.deployment.image.pullPolicy }}
          command: ["/smd-init"]
          env:
            - name: SMD_DBHOST
              value: {{ .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc.cluster.local
            - name: SMD_DBPORT
              value: "{{ .Values.postgresql.service.ports.postgresql }}"
            - name: SMD_DBOPTS
              value: sslmode=disable
            - name: SMD_DBUSER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-pg-smd
                  key: username
            - name: SMD_DBPASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-pg-smd
                  key: password
            - name: SMD_DBNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-pg-smd
                  key: database
      restartPolicy: OnFailure
  backoffLimit: 4
