---
apiVersion: batch/v1
kind: Job
metadata:
  name: bss
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      containers:
        - name: bss-init
          image: {{ .Values.bss.deployment.image.repository }}/{{ .Values.bss.deployment.image.name }}:{{ .Values.bss.deployment.image.tag }}
          imagePullPolicy: {{ .Values.bss.deployment.image.pullPolicy }}
          command: ["/usr/local/bin/bss-init"]
          env:
            - name: BSS_USESQL
              value: "true"
            - name: BSS_INSECURE
              value: "true"
            - name: BSS_DBHOST
              value: {{ .Release.Name }}-postgresql-bss.{{ .Release.Namespace }}.svc.cluster.local
            - name: BSS_DBNAME
              value: {{ .Values.bss.dbname }}
            - name: BSS_DBPORT
              value: "{{ .Values.postgres.service.port }}"
            - name: BSS_DBUSER
              value: bss-user
            - name: BSS_DBPASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgresql-bss
                  key: password
      restartPolicy: OnFailure
  backoffLimit: 4
