---
apiVersion: batch/v1
kind: Job
metadata:
  name: bss
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      containers:
        - name: bss-init
          image: {{ .Values.bss.deployment.image.repository }}/{{ .Values.bss.deployment.image.name }}:{{ .Values.bss.deployment.image.tag }}
          imagePullPolicy: {{ .Values.bss.deployment.image.pullPolicy }}
          command: ["/usr/local/bin/bss-init"]
          env:
            - name: BSS_USESQL
              value: "true"
            - name: BSS_INSECURE
              value: "true"
            - name: BSS_DBHOST
              value: {{ .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc.cluster.local
            - name: BSS_DBPORT
              value: {{ .Values.postgresql.service.ports.postgresql }}
              value: "{{ .Values.postgresql.service.ports.postgresql }}"
            - name: BSS_DBUSER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-pg-bss
                  key: username
            - name: BSS_DBPASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-pg-bss
                  key: password
            - name: BSS_DBNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-pg-bss
                  key: database
      restartPolicy: OnFailure
  backoffLimit: 4
