- name: Drop minio Quadlet files
  ansible.builtin.template:
    src: minio/minio.service.j2
    dest: '/etc/containers/systemd/minio.container'
    owner: root
    group: root
    mode: '{{ file_perm_rw }}'
  notify: Reload systemd

- name: Start minio service
  ansible.builtin.service:
    name: minio.service
    state: started
    enabled: true
    daemon_reload: true
