- name: Drop registry Quadlet files
  ansible.builtin.template:
    src: registry/registry.service.j2
    dest: '/etc/containers/systemd/registry.container'
    owner: root
    group: root
    mode: '{{ file_perm_rw }}'
  notify: Reload systemd

- name: Start registry service
  ansible.builtin.service:
    name: registry.service
    state: started
    enabled: true
    daemon_reload: true
