services:
  coredhcp:
    image: ghcr.io/openchami/coredhcp:v0.3.1
    container_name: coredhcp
    hostname: coredhcp
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - ./configs/coredhcp.yaml:/etc/coredhcp/config.yaml:ro
      - step-root-ca:/root_ca/:ro
    command:
      - "/coredhcp"
      - "-L"
      - "debug"
    healthcheck:
      test: "dhcping -c {{cluster_boot_ip}} -s {{cluster_boot_ip}} -h 00:00:00:00:00:00"
      interval: 5s
      timeout: 10s
      retries: 60
    depends_on:
      smd:
        condition: service_healthy
