services:
  coredhcp:
    image: ghcr.io/openchami/coresmd:v0.0.1
    container_name: coredhcp
    hostname: coredhcp
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - ./configs/coredhcp.yaml:/etc/coredhcp/config.yaml:ro
      - step-root-ca:/root_ca/:ro
    command:
      - "-L"
      - "debug"
    healthcheck:
      test: pgrep coredhcp
      interval: 5s
      timeout: 10s
      retries: 60
    depends_on:
      smd:
        condition: service_healthy
