services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.17
    environment:
      - ETCD_UNSUPPORTED_ARCH=arm64
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
    networks:
      - internal
      - jwt-internal
