services:
###
# SMD Init and Server Containers
###
  # sets up postgres for SMD data
  smd-init:
    image: ghcr.io/openchami/smd:v2.17.7
    container_name: smd-init
    hostname: smd-init
    environment:
      - SMD_DBHOST=postgres
      - SMD_DBPORT=5432
      - SMD_DBNAME=hmsds
      - SMD_DBUSER=smd-user
      - SMD_DBPASS=${SMD_POSTGRES_PASSWORD} # Set in .env file
      - SMD_DBOPTS=sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal
    entrypoint:
      - /smd-init
  # SMD
  smd:
    image: ghcr.io/openchami/smd:v2.17.7
    container_name: smd
    hostname: smd
    environment:
      - SMD_DBHOST=postgres
      - SMD_DBPORT=5432
      - SMD_DBNAME=hmsds
      - SMD_DBUSER=smd-user
      - SMD_DBPASS=${SMD_POSTGRES_PASSWORD} # Set in .env file
      - SMD_DBOPTS=sslmode=disable
      # - SMD_JWKS_URL=http://opaal:3333/keys
      - SMD_JWKS_URL= # To help PCS querying hardware from SMD/HSM hardware inventory without authentication
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=hms
      - CRAY_VAULT_AUTH_PATH=auth/token/create
      - CRAY_VAULT_ROLE_FILE=configs/namespace
      - CRAY_VAULT_JWT_FILE=configs/token
      - SMD_WVAULT=true
      - SMD_RVAULT=true
    volumes:
      - ./configs/namespace:/configs/namespace
      - ./configs/token:/configs/token
    depends_on:
      postgres:
        condition: service_healthy
      smd-init:
        condition: service_completed_successfully
      opaal:
        condition: service_healthy
    ports:
      - "27779:27779"
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "http://localhost:27779/hsm/v2/service/ready"]
      interval: 5s
      retries: 60
      start_period: 20s
      timeout: 10s
    networks:
      - internal
###
# BSS Init and Server Containers
###
# sets up postgres for BSS data
  bss-init:
    image: ghcr.io/openchami/bss:v1.32.0
    container_name: bss-init
    hostname: bss-init
    environment:
      - BSS_USESQL=true
      - BSS_INSECURE=true
      - BSS_DBHOST=postgres
      - BSS_DBPORT=5432
      - BSS_DBNAME=bssdb
      - BSS_DBUSER=bss-user
      - BSS_DBPASS=${BSS_POSTGRES_PASSWORD} # Set in .env file
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal
    entrypoint:
      - /usr/local/bin/bss-init
  # boot-script-service
  bss:
    image: ghcr.io/openchami/bss:v1.32.0
    container_name: bss
    hostname: bss
    environment:
      - BSS_USESQL=true
      - BSS_INSECURE=true
      - BSS_DEBUG=true
      - BSS_DBHOST=postgres
      - BSS_DBPORT=5432
      - BSS_DBNAME=bssdb
      - BSS_DBUSER=bss-user
      - BSS_DBPASS=${BSS_POSTGRES_PASSWORD} # Set in .env file
      - BSS_JWKS_URL=http://opaal:3333/keys
      - BSS_OAUTH2_ADMIN_BASE_URL=http://opaal:3333
      - BSS_OAUTH2_PUBLIC_BASE_URL=http://opaal:3333
      - BSS_IPXE_SERVER=${SYSTEM_NAME}.${SYSTEM_DOMAIN}
      - BSS_CHAIN_PROTO=https
      - BSS_BOOTSCRIPT_NOTIFY_URL=http://tpm-manager:27780/Node
    #ports:
    #  - '27778:27778'
    depends_on:
      postgres:
        condition: service_healthy
      smd:
        condition: service_healthy
      bss-init:
        condition: service_completed_successfully
      opaal:
        condition: service_healthy
    networks:
      - internal
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "http://localhost:27778/boot/v1/service/status"]
      interval: 5s
      timeout: 10s
      retries: 60
###
# cloud-init Server Container
###
  # cloud-init server, with the secure route disabled for now
  cloud-init:
    image: ghcr.io/openchami/cloud-init:v0.1.1
    container_name: cloud-init
    hostname: cloud-init
    environment:
      - LISTEN_ADDR=:27777
      - SMD_URL=http://smd:27779
      - OPAAL_URL=http://opaal:3333
    ports:
      - '27777:27777'
    depends_on:
      smd:
        condition: service_healthy
      opaal:
        condition: service_healthy
    networks:
      - internal
