services:
  pcs:
    image: ghcr.io/openchami/pcs
    container_name: pcs
    restart: always
    networks:
      - internal
      - jwt-internal
    environment:
      SMS_SERVER: http://smd:27779
      VAULT_ENABLED: "true"
      VAULT_ADDR: "http://vault:8200"
      VAULT_KEYPATH: "secret/hms-creds"
      API_URL: "http://localhost"
      API_SERVER_PORT: ":28007"
      API_BASE_PATH: "/v1"
      CRAY_VAULT_JWT_FILE: /etc/keys/token
      CRAY_VAULT_ROLE_FILE: /etc/keys/role
      CRAY_VAULT_AUTH_PATH: auth/jwt/login
      LOG_LEVEL: DEBUG
    volumes:
      - ./keys:/etc/keys
    ports:
      - 28007:28007

    # TODO: try [depends_on][1]
    # 1: https://github.com/OpenCHAMI/power-control/blob/46d7f18ccea0687da383d3ad02ee1b5a0581c34f/docker-compose.test.ct.yaml#L321
    # depends_on:
    #   - etcd # needed to bring up PCS
    #   - smd # needed to bring up PCS
    #   - vault-kv-enabler # needed for discovery of emulated hardware to succeed
    #   - emulator-loader # needed to bring up emulated hardware
    #   - wait-for-smd # needed to give PCS time for its initial hardware scan
