services:
  vault:
    hostname: vault
    container_name: vault
    image: docker.io/library/vault:1.5.5
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=hms
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_ADDR=http://vault:8200
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    networks:
      - internal
      - jwt-internal
