services:
  versity:
    image: ghcr.io/versity/versitygw:v0.22 
    container_name: versity
    hostname: versity
    restart: always
    networks:
      - internal
    volumes:
      - ./s3-storage/:/tmp/:rw
    environment:
      - ROOT_ACCESS_KEY=${VERSITY_ROOT_ACCESS_KEY} # Set in .env file
      - ROOT_SECRET_KEY={VERSITY_ROOT_SECRET_KEY} # Set in .env file
    command: -p :7070 posix /tmp # Uses port 7070 by default
    depends_on:
      acme-deploy-s3:
        condition: service_completed_successfully 
    healthcheck:
      test: ["CMD", "pgrep", "versitygw"]
      interval: 30s
      timeout: 10s
      retries: 5

  acme-register-s3:
    container_name: s3.openchami.cluster
    image: ghcr.io/openchami/acme.sh:v0.2.2
    networks:
      - cert-internal
    depends_on:
      step-ca:
        condition: service_healthy
    volumes:
      - step-root-ca:/root_ca/:ro
      - acme-certs:/root/.acme.sh
    entrypoint: ["/usr/bin/acme.sh", "--server", "https://step-ca:9000/acme/acme/directory", "--ca-bundle", "/root_ca/root_ca.crt", "-d", "s3.openchami.cluster", "--issue", "--standalone", "--force"]

  acme-deploy-s3:
    container_name: acme-deploy-s3
    image: ghcr.io/openchami/acme.sh:v0.2.2
    networks:
      - cert-internal
    depends_on:
      acme-register-s3:
        condition: service_completed_successfully
    volumes:
      - /:/root_ca/:ro
      - acme-certs:/root/.acme.sh
      - haproxy-certs:/root/certs/
    environment:
      - DEPLOY_HAPROXY_PEM_PATH=/root/certs/
    entrypoint: ["/usr/bin/acme.sh", "--server", "https://step-ca:9000/acme/acme/directory", "--ca-bundle", "/root_ca/root_ca.crt", "--deploy", "--deploy-hook", "haproxy", "--domain", "s3.openchami.cluster"]
