- name: Configure the {{ rhel_base_compute_image_name }} osimage
  ansible.builtin.template:
    src: "{{ rhel_base_compute_image_template }}"
    dest: "{{ openchami_work_dir }}/images/{{ rhel_base_compute_image_name }}-{{ rhel_tag }}.yaml"
    mode: '{{ file_perm_rw }}'

- name: Build {{ rhel_base_compute_image_name }} osimage
  block:
    - name: Build {{ rhel_base_compute_image_name }} osimage (This task will take some time)
      ansible.builtin.command:  
        cmd: >
          podman run --rm
          --device /dev/fuse
          --network host -e S3_ACCESS={{ minio_s3_username }} -e S3_SECRET={{ minio_s3_password }}
          {{ rhel_base_compute_mounts }}
          {{ image_build_name }}
          image-build --config config.yaml --log-level DEBUG
      changed_when: true
      register: build_base_compute_osimage
  rescue:
    - name: Failed to {{ rhel_base_compute_image_name }} osimage
      ansible.builtin.debug:
        msg: "{{ image_build_fail_msg }}. Error: {{ build_base_compute_osimage.stderr_lines }}"

- name: Verify the {{ rhel_base_compute_image_name }} created
  ansible.builtin.command: regctl repo ls {{ cluster_name }}.{{ cluster_domain }}:5000
  changed_when: false
  register: verify_base_compute_osimage

- name: Fail if {{ rhel_base_compute_image_name }} not created
  ansible.builtin.fail:
    msg: "Failed to build {{ rhel_base_compute_image_name }} osimage {{ rhel_base_compute_image }}"
  when: rhel_base_compute_image not in verify_base_compute_osimage.stdout_lines

- name: Verify {{ rhel_base_compute_image_name }} osimage output
  ansible.builtin.debug:
    msg: "{{ verify_base_compute_osimage.stdout_lines }}"
