- name: Import regctl tasks
  ansible.builtin.import_tasks: regctl.yaml

- name: Import s3 bucket tasks
  ansible.builtin.import_tasks: s3_bucket.yaml

- name: Import policy update tasks
  ansible.builtin.import_tasks: policy_update.yaml

- name: Import base image tasks
  ansible.builtin.import_tasks: base_image.yaml
  tags: base_image

- name: Import base compute image tasks
  ansible.builtin.import_tasks: base_compute_image.yaml
  tags: compute_image
