server:         # Server-related parameters when using as service
  host: 0.0.0.0
  port: 3334
  jwks:         # Set the JWKS uri to protect /generate route
    uri: ""
    retries: 5
smd:          # SMD-related parameters
  host: http://smd
  port: 27779
targets:        # targets to call with --target flag with CLI or "target" query param
  coredhcp: 
    templates: 
      - templates/coredhcp.jinja
  syslog: 
    templates: 
      - templates/syslog.jinja
  ansible: 
    templates: 
      - templates/ansible.jinja
  powerman: 
    templates: 
      - templates/powerman.jinja
  conman: 
    templates: 
      - templates/conman.jinja
