serve:
  cookies:
    same_site_mode: Lax

oidc:
  dynamic_client_registration:
    enabled: true
  subject_identifiers:
    supported_types:
      - public

oauth2:
  grant:
    jwt:
      jti_optional: true
      iat_optional: true
      max_ttl: 24h

strategies:
  access_token: jwt
