version: "0.0.1"
server:
  host: "opaal"
  port: 3333
  callback: "/oidc/callback"
  issuer: # Opaal-idp only uses this section of the config
    host: "opaal-idp"
    port: 3332

providers:
  ochami: "http://localhost:8080"

authentication:
  state: ""
  test-all: false
  clients:
    - id: "ochami"
      secret: "ochami"
      name: "ochami"
      issuer: "http://opaal-idp:3332"
      redirect-uris:
        - "http://opaal:3333/oidc/callback"

authorization:
  token:
    forwarding: false
    refresh: false
    duration: 16h
    scope:
      - smd.read
  token-duration: 16h
  token-forwarding: false
  key-path: ./keys
  endpoints:
    issuer: http://hydra:4444
    config: http://hydra:4444/.well-known/openid-configuration
    jwks: http://hydra:4444/.well-known/jwks.json
    #identities: http://127.0.0.1:4434/admin/identities
    trusted-issuers: http://hydra:4445/admin/trust/grants/jwt-bearer/issuers
    login: http://hydra:4433/self-service/login/api
    clients: http://hydra:4445/admin/clients
    authorize: http://hydra:4444/oauth2/auth
    register: http://hydra:4444/oauth2/register
    token: http://hydra:4444/oauth2/token


options:
  run-once: true
  open-browser: false
  flow: authorization_code
  cache-only: false
  verbose: true

examples:
  host: 127.0.0.1
  port: 3330
