version: '3.7'

services:
  step-ca:
    hostname: SI.ca
    container_name: SI.ca
    image: ghcr.io/openchami/local-ca:acme
    ports: 
      - "443:443"
    healthcheck: 
      test: ["CMD-SHELL", "step", "ca", "health", "--ca-url", "https://SI.ca", "--root", "$(step path)/certs/root_ca.crt"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - internal
    volumes:
      - ./configs/step-ca:/mnt
  krakend-ce:
    hostname: SI.krakend
    container_name: SI.krakend
    image: ghcr.io/openchami/krakend:acme
    environment:
      - KRAKEND_CONFIG=/etc/krakend/krakend.json
      - KRAKEND_PORT=8080
    healthcheck:
      #this health check happens inside the krakend container, the /root/.acme.sh/SI.krakend_ecc/SI.krakend.cer file is the certificate chain for the internal CA.
      test: ["CMD-SHELL", "CURL_CA_BUNDLE=/root/.acme.sh/SI.krakend_ecc/SI.krakend.cer", "curl", "-f", "https:/SI.krakend:8080/__health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    depends_on:
      - bss
      - smd
      - step-ca
    ports:
      - "8080:8080"
    networks:
      - internal
    # ./configs/step-ca/config/defaults.json is auto-generated by the step-ca container, it doesn't need manual population.
    volumes:
      - ./configs/krakend.json:/etc/krakend.json:ro
      - ./configs/step-ca/config/defaults.json:/mnt/defaults.json:ro
