version: '3.7'

services:
  step-ca-tests:
    hostname: step-ca-tests
    container_name: step-ca-tests
    image: cgr.dev/chainguard/wolfi-base
    ports: 
      - "80:80"
    networks:
      - internal
    volumes:
      - ./configs/step-ca/config/defaults.json:/mnt/defaults.json:ro
    depends_on:
      step-ca:
        condition: service_healthy
    command: sh -c "apk add socat openssl wget curl step jq; wget -O get.acme.sh https://get.acme.sh; sh get.acme.sh force; step ca bootstrap --ca-url=https://SI.ca --fingerprint=$(cat /mnt/defaults.json | jq '.fingerprint' -r) --install; /root/.acme.sh/acme.sh --force --issue --standalone -d step-ca-tests --server https://SI.ca/acme/acme/directory --ca-bundle \$(step path)/certs/root_ca.crt;"
