version: '3.7'

services:
  
  krakend-ce:
    container_name: krakend-ce
    image: devopsfaith/krakend
    environment:
      - KRAKEND_CONFIG=/etc/krakend/krakend.json
      - KRAKEND_PORT=8080
    hostname: krakend-ce
    depends_on:
      - bss
      - smd
    ports:
      - "8080:8080"
    networks:
      - internal
    volumes:
      - ./krakend.json:/etc/krakend/krakend.json:ro
