version: '3.7'

services:
  step-ca:
    hostname: SI.ca
    container_name: SI.ca
    image: ghcr.io/openchami/local-ca:acme
    ports: 
      - "443:443"
    healthcheck: 
      test: ["CMD", "step", "ca", "health", "--ca-url", "https://SI.ca", "--root", "$(step path)/certs/root_ca.crt"]
    networks:
      - internal
    volumes:
      - ./configs/step-ca:/mnt
  krakend-ce:
    hostname: SI.krakend
    container_name: SI.krakend
    image: ghcr.io/openchami/krakend:acme
    environment:
      - KRAKEND_CONFIG=/etc/krakend/krakend.json
      - KRAKEND_PORT=8080
    healthcheck:
      test: ["CMD", "CURL_CA_BUNDLE=/root/.acme.sh/SI.krakend_ecc/SI.krakend.cer", "curl", "-f", "https:/SI.endpoint:8080/__health"]
    depends_on:
      - bss
      - smd
      - step-ca
    ports:
      - "8080:8080"
    networks:
      - internal
    volumes:
      - ./configs/krakend.json:/etc/krakend/krakend.json:ro
      - ./configs/step-ca/config/defaults.json:/mnt/defaults.json:ro
