version: '3.7'

## Because hardcoding passwords is bad, we use openssl to generate a random password
## and store it in a .env file.  This file is not checked into git, so it is not
## shared with anyone else.  This is a temporary solution until we can use docker secrets.
## The generate-creds.sh script performs the following commands.
# echo "POSTGRES_PASSWORD=$(openssl rand -base64 32 | openssl dgst | cut -d' ' -f2)" > .env
# echo "SMD_POSTGRES_PASSWORD=$(openssl rand -base64 32 | openssl dgst | cut -d' ' -f2)" >> .env
# echo "BSS_POSTGRES_PASSWORD=$(openssl rand -base64 32 | openssl dgst | cut -d' ' -f2)" >> .env
# echo "HYDRA_POSTGRES_PASSWORD=$(openssl rand -base64 32 | openssl dgst | cut -d' ' -f2)" >> .env

services:
###
# SMD Init and Server Containers (auth disabled)
###
  # sets up postgres for SMD data
  smd-init-noauth:
    image: ghcr.io/openchami/smd:v2.15.0
    container_name: smd-init-noauth
    hostname: smd-init-noauth
    environment:
      - SMD_DBHOST=postgres-noauth
      - SMD_DBPORT=5432
      - SMD_DBUSER=smd-user
      - SMD_DBPASS=${SMD_POSTGRES_PASSWORD} # Set in .env file
      - SMD_DBNAME=hmsds
      - SMD_DBOPTS=sslmode=disable
    depends_on:
      postgres-noauth:
        condition: service_healthy
    networks:
      - internal-noauth
    entrypoint:
      - /smd-init
  # SMD with auth requirement disabled
  smd-noauth:
    image: ghcr.io/openchami/smd:v2.15.0
    container_name: smd-noauth
    hostname: smd-noauth
    environment:
      - SMD_DBHOST=postgres-noauth
      - SMD_DBPORT=5432
      - SMD_DBNAME=hmsds
      - SMD_DBUSER=smd-user
      - SMD_DBPASS=${SMD_POSTGRES_PASSWORD} # Set in .env file
      - SMD_DBOPTS=sslmode=disable
    depends_on:
      postgres-noauth:
        condition: service_healthy
      smd-init-noauth:
        condition: service_completed_successfully
    ports:
      - "27799:27779"
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "http://localhost:27779/hsm/v2/service/ready"]
      interval: 5s
      retries: 60
      start_period: 20s
      timeout: 10s
    networks:
      - internal-noauth
###
# BSS Init and Server Containers (auth disabled)
###
# sets up postgres for BSS data
  bss-init-noauth:
    hostname: bss-init-noauth
    container_name: bss-init-noauth
    image: ghcr.io/openchami/bss:v1.30.2
    environment:
      - BSS_USESQL=true
      - BSS_INSECURE=true
      - BSS_DBHOST=postgres-noauth
      - BSS_DBPORT=5432
      - BSS_DBNAME=bssdb
      - BSS_DBUSER=bss-user
      - BSS_DBPASS=${BSS_POSTGRES_PASSWORD} # Set in .env file
    depends_on:
      postgres-noauth:
        condition: service_healthy
    networks:
      - internal-noauth
    entrypoint:
      - /usr/local/bin/bss-init
  # boot-script-service
  bss-noauth:
    hostname: bss-noauth
    container_name: bss-noauth
    image: ghcr.io/openchami/bss:v1.30.2
    environment:
      - BSS_USESQL=true
      - BSS_INSECURE=true
      - BSS_DBHOST=postgres-noauth
      - BSS_DBPORT=5432
      - BSS_DBNAME=bssdb
      - BSS_DBUSER=bss-user
      - BSS_DBPASS=${BSS_POSTGRES_PASSWORD} # Set in .env file
      - HSM_URL=http://smd-noauth:27779
    ports:
      - '27788:27778'
    depends_on:
      postgres-noauth:
        condition: service_healthy
      smd-noauth:
        condition: service_healthy
      bss-init-noauth:
        condition: service_completed_successfully
    networks:
      - internal-noauth
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "http://localhost:27778/boot/v1/service/status"]
      interval: 5s
      timeout: 10s
      retries: 60
  dnsmasq:
    image: ghcr.io/openchami/dnsmasq:dynamic
    container_name: dnsmasq-dhcp-noauth
    hostname: dnsmasq-dhcp-noauth
    environment:
      - smd_endpoint=localhost
      - smd_port=27799
      - bss_endpoint=localhost
      - bss_port=27788
    depends_on:
      bss-noauth:
        condition: service_healthy
      smd-noauth:
        condition: service_healthy
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: pgrep dnsmasq
      interval: 5s
      timeout: 10s
      retries: 60
