---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app: postgres
spec:
  replicas: {{ .Values.postgres.deployment.replicaCount }}
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.deployment.image.repository }}/{{ .Values.postgres.deployment.image.name }}:{{ .Values.postgres.deployment.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.postgres.deployment.image.pullPolicy }}
          ports:
            - name: postgres
              containerPort: {{ .Values.postgres.deployment.containerPort }}
              protocol: TCP
          env:
            - name: POSTGRES_DB
              value: {{ .Values.init.dbname }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: password
