apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: postgres
spec:
  type: {{ .Values.postgres.service.type }}
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.deployment.containerPort }}
      name: postgres
  selector:
    app: postgres
