# site.yml
- name: Deploy Keylime services on Rocky Linux
  hosts: keylime_agents
  become: true
  roles:
    - common              # Prepare system (TPM, packages, env)
    - keylime_agent       # Set up Keylime Agent service (after Registrar)
