apiVersion: v1
data:
  dnsmasq.conf: |
    port=0
    user=root
    dhcp-authoritative
    log-dhcp
    domain=.local
    dhcp-option=option:domain-search,.local
    #TODO the next 4 options should be dynamic, I don't know how we want to populate these
    dhcp-range=192.168.0.50,192.168.0.150,255.255.255.0,12h
    dhcp-option=option:mtu,1500
    dhcp-hostsfile=/etc/dhcp-hostsfile
    dhcp-optsfile=/etc/dhcp-optsfile
    enable-tftp
    tftp-root=/usr/share/ipxe
  init.sh: |
    smd.py
    update_loop.sh &
    dnsmasq -d --log-dhcp
kind: ConfigMap
metadata:
  name: dnsmasq-config
  namespace: {{ .Release.Namespace }}
