apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: dnsmasq-dhcp
  {{- with .Values.dnsmasq.service.dhcp.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.dnsmasq.service.dhcp.type }}
  ports:
    - port: {{ .Values.dnsmasq.service.dhcp.port }}
      targetPort: {{ .Values.dnsmasq.deployment.dhcp_port}}
      name: dnsmasq-dhcp
      protocol: UDP
  selector:
    app: dnsmasq
  {{- with .Values.dnsmasq.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
