apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: dnsmasq-tftp
  {{- with .Values.dnsmasq.service.tftp.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.dnsmasq.service.tftp.type }}
  ports:
    - port: {{ .Values.dnsmasq.service.tftp.port }}
      targetPort: {{ .Values.dnsmasq.deployment.tftp_port}}
      name: dnsmasq-tftp
      protocol: UDP
  selector:
    app: dnsmasq
  {{- with .Values.dnsmasq.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
