apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: coredhcp
  {{- with .Values.coredhcp.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.coredhcp.service.type }}
  ports:
    - port: {{ .Values.coredhcp.service.dhcp.port }}
      targetPort: 67
      name: dhcp
      protocol: UDP
    - port: {{ .Values.coredhcp.service.tftp.port }}
      targetPort: 69
      name: tftp
      protocol: UDP
  selector:
    app: coredhcp
