version: "0.0.1"
server:
  host: "0.0.0.0"
  port: 3333
  callback: "/oidc/callback"

providers:
  gitlab: "https://gitlab.newmexicoconsortium.org"

authentication:
  state: ""
  test-all: false
  clients:
    - id: "7c0fab1153674a258a705976fcb9468350df3addd91de4ec622fc9ed24bfbcdd"
      secret: "a9a8bc55b0cd99236756093adc00ab17855fa507ce106b8038e7f9390ef2ad99"
      name: "gitlab"
      issuer: "http://gitlab.newmexicoconsortium.org"
      scope:
        - "openid"
        - "profile"
        - "email"
      redirect-uris:
        - "http://opaal:3333/oidc/callback"

authorization:
  token:
    forwarding: false
    refresh: false
    duration: 16h
    scope:
      - smd.read
  token-duration: 16h
  token-forwarding: false
  key-path: ./keys
  endpoints:
    issuer: http://hydra:4444
    config: http://hydra:4444/.well-known/openid-configuration
    jwks: http://hydra:4444/.well-known/jwks.json
    #identities: http://hydra:4434/admin/identities
    trusted-issuers: http://hydra:4445/admin/trust/grants/jwt-bearer/issuers
    #login: http://127.0.0.1:4433/self-service/login/api
    clients: http://hydra:4445/admin/clients
    authorize: http://hydra:4444/oauth2/auth
    register: http://hydra:4444/oauth2/register
    token: http://hydra:4444/oauth2/token


options:
  run-once: true
  open-browser: false
  flow: authorization_code
  cache-only: false
  verbose: true
