---
- name: Generate access token
  ansible.builtin.shell: sudo bash -lc 'gen_access_token'
  register: access_token_result
  changed_when: false

- name: Set ochami_env
  ansible.builtin.set_fact:
    ochami_env: "{{ { cluster_env_key: access_token_result.stdout } }}"
